//! CUDA C++ code generation from [`KernelProgram`].
//!
//! The generated translation unit is self-contained and exports the C
//! interface from `design.md`:
//!
//! ```c
//! Prog* make_module();
//! void destroy_module(Prog*);
//! uint64_t scratch_size(Prog*);
//! uint64_t num_outputs(Prog*);   uint64_t output_size(Prog*, uint64_t);
//! uint64_t num_inputs(Prog*);    uint64_t input_size(Prog*, uint64_t);
//! void set_input(Prog*, uint64_t, void*);
//! void set_output(Prog*, uint64_t, void*);
//! void set_scratch_buf(Prog*, void*);
//! cudaError_t run(Prog*, cudaStream_t);
//! ```
//!
//! BabyBear arithmetic operates on the canonical `u32` representation; the
//! modulus is a compile-time constant so nvcc strength-reduces the `%`.

use std::fmt::Write;

use crate::{
    ir::{BinOp, ReduceOp, ScalarType},
    kernel_ir::{BufferKind, KExpr, Kernel, KernelProgram, LaunchShape, LinearLayout, Stmt, ValId},
};

const PRELUDE: &str = r#"// Auto-generated by crypto-compiler. Do not edit.
#include <cuda_runtime.h>
#include <cstdint>
#include <cstring>

#define BB_P 2013265921u

static __device__ __forceinline__ uint32_t bb_add(uint32_t a, uint32_t b) {
    uint32_t s = a + b;
    return s >= BB_P ? s - BB_P : s;
}
static __device__ __forceinline__ uint32_t bb_sub(uint32_t a, uint32_t b) {
    return a >= b ? a - b : a + (BB_P - b);
}
static __device__ __forceinline__ uint32_t bb_mul(uint32_t a, uint32_t b) {
    return (uint32_t)(((unsigned long long)a * (unsigned long long)b) % BB_P);
}
"#;

pub fn generate_cuda(p: &KernelProgram) -> String {
    let mut s = String::new();
    s.push_str(PRELUDE);
    s.push('\n');

    for k in &p.kernels {
        gen_kernel(&mut s, p, k);
        s.push('\n');
    }
    gen_host(&mut s, p);
    s
}

fn val(v: ValId) -> String {
    format!("v{}", v.0)
}

fn gen_kernel(s: &mut String, p: &KernelProgram, k: &Kernel) {
    let params = k
        .params
        .iter()
        .map(|&(buf, writable)| {
            let cq = if writable { "" } else { "const " };
            format!("{cq}uint32_t* __restrict__ b{buf}")
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(s, "__global__ void {}({params}) {{", k.name).unwrap();

    match k.launch {
        LaunchShape::Flat { n } => {
            writeln!(
                s,
                "    const uint32_t idx = blockIdx.x * blockDim.x + threadIdx.x;"
            )
            .unwrap();
            if k.grid * k.block > n {
                writeln!(s, "    if (idx >= {n}u) return;").unwrap();
            }
        }
        LaunchShape::Grid { .. } => {}
    }
    gen_stmts(s, p, k, &k.body, 1);
    writeln!(s, "}}").unwrap();
}

fn gen_stmts(s: &mut String, p: &KernelProgram, k: &Kernel, stmts: &[Stmt], depth: usize) {
    let pad = "    ".repeat(depth);
    for stmt in stmts {
        match stmt {
            Stmt::Def { dst, expr } => {
                writeln!(
                    s,
                    "{pad}const uint32_t {} = {};",
                    val(*dst),
                    expr_str(p, k, expr)
                )
                .unwrap();
            }
            Stmt::DefAcc { dst, init } => {
                writeln!(s, "{pad}uint32_t {} = {};", val(*dst), val(*init)).unwrap();
            }
            Stmt::Loop { var, bound, body } => {
                let v = val(*var);
                writeln!(s, "{pad}for (uint32_t {v} = 0u; {v} < {bound}u; ++{v}) {{").unwrap();
                gen_stmts(s, p, k, body, depth + 1);
                writeln!(s, "{pad}}}").unwrap();
            }
            Stmt::Par {
                bound,
                idx,
                attr,
                body,
            } => {
                let attr = attr.as_ref().expect("layout_infer must run before codegen");
                let v = val(*idx);
                if attr.layout.is_identity() {
                    // Identity layout is the strided factorization
                    // `i = s * blockDim + t`, realized as a strided loop
                    // whose condition doubles as the bounds guard.
                    writeln!(
                        s,
                        "{pad}for (uint32_t {v} = threadIdx.x; {v} < {bound}u; {v} += blockDim.x) {{"
                    )
                    .unwrap();
                    gen_stmts(s, p, k, body, depth + 1);
                } else {
                    let seq = attr.seq_size;
                    let phys = format!("{v}_s * blockDim.x + threadIdx.x");
                    writeln!(
                        s,
                        "{pad}for (uint32_t {v}_s = 0u; {v}_s < {seq}u; ++{v}_s) {{"
                    )
                    .unwrap();
                    writeln!(
                        s,
                        "{pad}    const uint32_t {v} = {};",
                        ll_apply_str(&attr.layout, &format!("({phys})"))
                    )
                    .unwrap();
                    writeln!(s, "{pad}    if ({v} >= {bound}u) continue;").unwrap();
                    gen_stmts(s, p, k, body, depth + 1);
                }
                writeln!(s, "{pad}}}").unwrap();
            }
            Stmt::Alloc { buf } => {
                let decl = &p.buffers[*buf];
                let phys_len = match &decl.layout {
                    Some(l) if !l.is_identity() => 1usize << l.bases.len(),
                    _ => decl.len(),
                };
                writeln!(s, "{pad}__shared__ uint32_t b{buf}[{phys_len}];").unwrap();
            }
            Stmt::Sync => {
                writeln!(s, "{pad}__syncthreads();").unwrap();
            }
            Stmt::AccUpdate { acc, op, ty, value } => {
                let a = val(*acc);
                let v = val(*value);
                let rhs = match (ty, op) {
                    (ScalarType::BabyBear, ReduceOp::Add) => format!("bb_add({a}, {v})"),
                    (ScalarType::BabyBear, ReduceOp::Mul) => format!("bb_mul({a}, {v})"),
                    (_, ReduceOp::Add) => format!("{a} + {v}"),
                    (_, ReduceOp::Mul) => format!("{a} * {v}"),
                };
                writeln!(s, "{pad}{a} = {rhs};").unwrap();
            }
            Stmt::Store { buf, index, value } => {
                writeln!(
                    s,
                    "{pad}b{buf}[{}] = {};",
                    index_str(p, *buf, *index),
                    val(*value)
                )
                .unwrap();
            }
        }
    }
}

/// Physical index expression for `buf[index]`, applying the buffer's linear
/// layout when it is non-trivial.
fn index_str(p: &KernelProgram, buf: usize, index: ValId) -> String {
    match &p.buffers[buf].layout {
        Some(l) if !l.is_identity() => ll_apply_str(l, &val(index)),
        _ => val(index),
    }
}

/// C expression applying a [`LinearLayout`] to `x`: the XOR of the bases
/// selected by the bits of `x`.
fn ll_apply_str(layout: &LinearLayout, x: &str) -> String {
    layout
        .bases
        .iter()
        .enumerate()
        .map(|(i, &b)| format!("((({x} >> {i}) & 1u) * {b}u)"))
        .collect::<Vec<_>>()
        .join(" ^ ")
}

fn expr_str(p: &KernelProgram, k: &Kernel, expr: &KExpr) -> String {
    match expr {
        KExpr::ConstU32(c) | KExpr::ConstField(c) => format!("{c}u"),
        KExpr::OuterIdx => match k.launch {
            LaunchShape::Flat { .. } => "idx".into(),
            LaunchShape::Grid { .. } => "blockIdx.x".into(),
        },
        KExpr::Bin { op, ty, lhs, rhs } => {
            let a = val(*lhs);
            let b = val(*rhs);
            if *ty == ScalarType::BabyBear {
                match op {
                    BinOp::Add => format!("bb_add({a}, {b})"),
                    BinOp::Sub => format!("bb_sub({a}, {b})"),
                    BinOp::Mul => format!("bb_mul({a}, {b})"),
                    _ => unreachable!("op {op:?} is not defined on BabyBear"),
                }
            } else {
                let c_op = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Rem => "%",
                    BinOp::Lt => "<",
                    BinOp::Le => "<=",
                    BinOp::Eq => "==",
                };
                match op {
                    BinOp::Lt | BinOp::Le | BinOp::Eq => format!("(uint32_t)({a} {c_op} {b})"),
                    _ => format!("{a} {c_op} {b}"),
                }
            }
        }
        KExpr::Select {
            cond,
            then_val,
            else_val,
        } => format!("{} ? {} : {}", val(*cond), val(*then_val), val(*else_val)),
        KExpr::Load { buf, index } => format!("b{buf}[{}]", index_str(p, *buf, *index)),
    }
}

/// C expression for a buffer pointer inside `run`, respecting constness.
fn buf_arg(p: &KernelProgram, buf: usize, writable: bool) -> String {
    let cq = if writable { "" } else { "const " };
    match p.buffers[buf].kind {
        BufferKind::Input(k) => format!("({cq}uint32_t*)p->inputs[{k}]"),
        BufferKind::Output(k) => format!("({cq}uint32_t*)p->outputs[{k}]"),
        BufferKind::Scratch { offset } => {
            format!("({cq}uint32_t*)((char*)p->scratch + {offset})")
        }
        BufferKind::Shared => unreachable!("shared buffers are never kernel parameters"),
    }
}

fn gen_host(s: &mut String, p: &KernelProgram) {
    let n_in = p.input_bufs.len();
    let n_out = p.output_bufs.len();
    let in_sizes = p
        .input_bufs
        .iter()
        .map(|&b| format!("{}ull", p.buffers[b].size_bytes()))
        .collect::<Vec<_>>()
        .join(", ");
    let out_sizes = p
        .output_bufs
        .iter()
        .map(|&b| format!("{}ull", p.buffers[b].size_bytes()))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(
        s,
        r#"struct Prog {{
    void* inputs[{in_cap}];
    void* outputs[{out_cap}];
    void* scratch;
}};

static const uint64_t kInputSizes[{in_cap}] = {{{in_sizes}}};
static const uint64_t kOutputSizes[{out_cap}] = {{{out_sizes}}};

extern "C" Prog* make_module() {{
    Prog* p = new Prog;
    std::memset(p, 0, sizeof(Prog));
    return p;
}}
extern "C" void destroy_module(Prog* p) {{ delete p; }}
extern "C" uint64_t scratch_size(Prog*) {{ return {scratch}ull; }}
extern "C" uint64_t num_outputs(Prog*) {{ return {n_out}ull; }}
extern "C" uint64_t output_size(Prog*, uint64_t i) {{ return kOutputSizes[i]; }}
extern "C" uint64_t num_inputs(Prog*) {{ return {n_in}ull; }}
extern "C" uint64_t input_size(Prog*, uint64_t i) {{ return kInputSizes[i]; }}
extern "C" void set_input(Prog* p, uint64_t i, void* ptr) {{ p->inputs[i] = ptr; }}
extern "C" void set_output(Prog* p, uint64_t i, void* ptr) {{ p->outputs[i] = ptr; }}
extern "C" void set_scratch_buf(Prog* p, void* ptr) {{ p->scratch = ptr; }}
"#,
        in_cap = n_in.max(1),
        out_cap = n_out.max(1),
        in_sizes = if n_in == 0 { "0ull".into() } else { in_sizes },
        out_sizes = if n_out == 0 { "0ull".into() } else { out_sizes },
        scratch = p.scratch_bytes,
        n_out = n_out,
        n_in = n_in,
    )
    .unwrap();

    writeln!(
        s,
        "extern \"C\" cudaError_t run(Prog* p, cudaStream_t stream) {{"
    )
    .unwrap();
    for k in &p.kernels {
        let args = k
            .params
            .iter()
            .map(|&(buf, writable)| buf_arg(p, buf, writable))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            s,
            "    {}<<<dim3({}u), dim3({}u), 0, stream>>>({args});",
            k.name, k.grid, k.block
        )
        .unwrap();
        writeln!(
            s,
            "    {{ cudaError_t err = cudaGetLastError(); if (err != cudaSuccess) return err; }}"
        )
        .unwrap();
    }
    writeln!(s, "    return cudaSuccess;\n}}").unwrap();
}
