//! CUDA C++ code generation from [`KernelProgram`].
//!
//! The generated translation unit is self-contained and exports the C
//! interface from `design.md`:
//!
//! ```c
//! Prog* make_module();
//! void destroy_module(Prog*);
//! uint64_t scratch_size(Prog*);
//! uint64_t num_outputs(Prog*);   uint64_t output_size(Prog*, uint64_t);
//! uint64_t num_inputs(Prog*);    uint64_t input_size(Prog*, uint64_t);
//! void set_input(Prog*, uint64_t, void*);
//! void set_output(Prog*, uint64_t, void*);
//! void set_scratch_buf(Prog*, void*);
//! cudaError_t run(Prog*, cudaStream_t);
//! ```
//!
//! Every SSA value is a `uint32_t` named `v{n}`; buffers are `b{n}` (global
//! pointers and shared arrays) or `r{n}` (per-thread register arrays, one
//! slot per sequential step of the accessing pars). Barriers are `Sync` ops
//! placed by `passes::insert_sync`; codegen emits a `__syncthreads()` for
//! each.
//!
//! BabyBear arithmetic operates on the canonical `u32` representation; the
//! modulus is a compile-time constant so nvcc strength-reduces the `%`.

use std::fmt::Write;

use crate::{
    ir::{BinOp, ScalarType, VarId},
    kernel_ir::{
        Access, BufId, BufferKind, IndexMap, Kernel, KernelProgram, LinearLayout, SSABlock,
        SSANode, SSAOpCode, SSARes,
    },
    quast::{CStrEmitter, Quast},
    CompileError,
};

const PRELUDE: &str = r#"// Auto-generated by crypto-compiler. Do not edit.
#include <cuda_runtime.h>
#include <cstdint>
#include <cstring>

#define BB_P 2013265921u

static __device__ __forceinline__ uint32_t bb_add(uint32_t a, uint32_t b) {
    uint32_t s = a + b;
    return s >= BB_P ? s - BB_P : s;
}
static __device__ __forceinline__ uint32_t bb_sub(uint32_t a, uint32_t b) {
    return a >= b ? a - b : a + (BB_P - b);
}
static __device__ __forceinline__ uint32_t bb_mul(uint32_t a, uint32_t b) {
    return (uint32_t)(((unsigned long long)a * (unsigned long long)b) % BB_P);
}
"#;

/// Generates the CUDA C++ translation unit for a [`KernelProgram`].
pub fn codegen(p: &KernelProgram) -> Result<String, CompileError> {
    let mut s = String::new();
    s.push_str(PRELUDE);
    s.push('\n');

    for k in &p.kernels {
        gen_kernel(&mut s, p, k)?;
        s.push('\n');
    }
    gen_host(&mut s, p);
    Ok(s)
}

fn val(v: SSARes) -> String {
    format!("v{}", v.0)
}

fn gen_kernel(s: &mut String, p: &KernelProgram, k: &Kernel) -> Result<(), CompileError> {
    let params = k
        .params
        .iter()
        .map(|&(buf, writable)| {
            let cq = if writable { "" } else { "const " };
            format!("{cq}uint32_t* __restrict__ b{}", buf.0)
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(s, "__global__ void {}({params}) {{", k.name).unwrap();
    if kernel_uses(k, k.grid_var()) {
        writeln!(s, "    const uint32_t {} = blockIdx.x;", val(k.grid_var())).unwrap();
    }
    gen_stmts(s, p, k, &k.grid.block.body, 1)?;
    writeln!(s, "}}").unwrap();
    Ok(())
}

/// Whether the kernel references `res` in any op or access index.
fn kernel_uses(k: &Kernel, res: SSARes) -> bool {
    let sym = VarId(res.0);
    k.ops().iter().any(|op| {
        op.operands.contains(&res)
            || match &op.opcode {
                SSAOpCode::Par { reads, writes, .. } => {
                    reads.iter().chain(writes).any(|a| match &a.index {
                        IndexMap::Affine { expr, .. } => quast_uses(expr, sym),
                        IndexMap::Linear(_) => false,
                    })
                }
                _ => false,
            }
    })
}

fn quast_uses(q: &Quast, v: VarId) -> bool {
    match q {
        Quast::Sym(s) => *s == v,
        Quast::Const(_) => false,
        Quast::Add(a, b) => quast_uses(a, v) || quast_uses(b, v),
        Quast::Mul(a, _) | Quast::FloorDiv(a, _) | Quast::Neg(a) => quast_uses(a, v),
    }
}

/// Emits a statement-level block body: `Alloc`, `Sync`, sequential `Loop`
/// and `Par` ops.
fn gen_stmts(
    s: &mut String,
    p: &KernelProgram,
    k: &Kernel,
    stmts: &[SSANode],
    depth: usize,
) -> Result<(), CompileError> {
    let pad = "    ".repeat(depth);
    for &sid in stmts {
        let op = k.op(sid);
        match &op.opcode {
            SSAOpCode::Alloc { buf } => {
                let decl = p.buffer(*buf);
                match decl.kind {
                    BufferKind::Shared => {
                        writeln!(
                            s,
                            "{pad}__shared__ uint32_t b{}[{}];",
                            buf.0,
                            decl.phys_len()
                        )
                        .unwrap();
                    }
                    BufferKind::Register => {
                        writeln!(s, "{pad}uint32_t r{}[{}];", buf.0, register_slots(k, *buf))
                            .unwrap();
                    }
                    _ => {
                        return Err(CompileError::Codegen(format!(
                            "buffer {} with kind {:?} cannot be declared in a kernel",
                            decl.name, decl.kind
                        )))
                    }
                }
            }
            SSAOpCode::Sync => {
                writeln!(s, "{pad}__syncthreads();").unwrap();
            }
            SSAOpCode::Loop { bound } => {
                let v = val(op.block.operands[0]);
                writeln!(s, "{pad}for (uint32_t {v} = 0u; {v} < {bound}u; ++{v}) {{").unwrap();
                gen_stmts(s, p, k, &op.block.body, depth + 1)?;
                writeln!(s, "{pad}}}").unwrap();
            }
            SSAOpCode::Par {
                bound,
                spans_grid,
                attr,
                reads,
                writes,
            } => {
                gen_par(
                    s,
                    p,
                    k,
                    *bound,
                    *spans_grid,
                    attr,
                    reads,
                    writes,
                    &op.block,
                    depth,
                )?;
            }
            other => unreachable!("scalar op {other:?} at statement level"),
        }
    }
    Ok(())
}

/// Register slots a buffer needs per thread: one per sequential step of the
/// pars accessing it.
fn register_slots(k: &Kernel, buf: BufId) -> usize {
    k.ops()
        .iter()
        .filter_map(|op| match &op.opcode {
            SSAOpCode::Par {
                attr,
                reads,
                writes,
                ..
            } if reads.iter().chain(writes).any(|a| a.buf == buf) => Some(
                attr.as_ref()
                    .expect("layout_infer must run before codegen")
                    .seq_size,
            ),
            _ => None,
        })
        .max()
        .unwrap_or(1)
}

#[allow(clippy::too_many_arguments)]
fn gen_par(
    s: &mut String,
    p: &KernelProgram,
    k: &Kernel,
    bound: usize,
    spans_grid: bool,
    attr: &Option<crate::kernel_ir::ParAttr>,
    reads: &[Access],
    writes: &[Access],
    block: &SSABlock,
    depth: usize,
) -> Result<(), CompileError> {
    let pad = "    ".repeat(depth);
    let attr = attr.as_ref().expect("layout_infer must run before codegen");
    let vid = block.operands[0];
    let v = val(vid);
    let uses_reg = reads
        .iter()
        .chain(writes)
        .any(|a| p.buffer(a.buf).kind == BufferKind::Register);

    if spans_grid {
        // The grid covers the whole domain: one point per thread.
        writeln!(
            s,
            "{pad}const uint32_t {v} = blockIdx.x * blockDim.x + threadIdx.x;"
        )
        .unwrap();
        let guard = k.grid.bound * k.block > bound;
        if guard {
            writeln!(s, "{pad}if ({v} < {bound}u) {{").unwrap();
        }
        let d = depth + usize::from(guard);
        gen_par_body(s, p, k, reads, writes, block, "0u", d)?;
        if guard {
            writeln!(s, "{pad}}}").unwrap();
        }
    } else if attr.layout.is_identity() {
        // Identity layout is the strided factorization `i = s * blockDim +
        // t`, realized as a strided loop whose condition doubles as the
        // bounds guard. The `_s` counter tracks the register slot.
        if uses_reg {
            writeln!(
                s,
                "{pad}for (uint32_t {v} = threadIdx.x, {v}_s = 0u; {v} < {bound}u; \
                 {v} += blockDim.x, ++{v}_s) {{"
            )
            .unwrap();
        } else {
            writeln!(
                s,
                "{pad}for (uint32_t {v} = threadIdx.x; {v} < {bound}u; {v} += blockDim.x) {{"
            )
            .unwrap();
        }
        gen_par_body(s, p, k, reads, writes, block, &format!("{v}_s"), depth + 1)?;
        writeln!(s, "{pad}}}").unwrap();
    } else {
        let seq = attr.seq_size;
        let phys = format!("({v}_s * blockDim.x + threadIdx.x)");
        writeln!(
            s,
            "{pad}for (uint32_t {v}_s = 0u; {v}_s < {seq}u; ++{v}_s) {{"
        )
        .unwrap();
        writeln!(
            s,
            "{pad}    const uint32_t {v} = {};",
            ll_apply_str(&attr.layout, &phys)
        )
        .unwrap();
        writeln!(s, "{pad}    if ({v} >= {bound}u) continue;").unwrap();
        gen_par_body(s, p, k, reads, writes, block, &format!("{v}_s"), depth + 1)?;
        writeln!(s, "{pad}}}").unwrap();
    }
    Ok(())
}

/// The body of one par point: bind the loaded block operands, run the SSA
/// ops, store the yields.
#[allow(clippy::too_many_arguments)]
fn gen_par_body(
    s: &mut String,
    p: &KernelProgram,
    k: &Kernel,
    reads: &[Access],
    writes: &[Access],
    block: &SSABlock,
    slot: &str,
    depth: usize,
) -> Result<(), CompileError> {
    let pad = "    ".repeat(depth);
    let vid = block.operands[0];
    for (i, access) in reads.iter().enumerate() {
        let operand = block.operands[1 + i];
        let src = access_str(p, access, vid, slot)?;
        writeln!(s, "{pad}const uint32_t {} = {src};", val(operand)).unwrap();
    }
    gen_ops(s, k, &block.body, depth)?;
    for (i, access) in writes.iter().enumerate() {
        let dst = access_str(p, access, vid, slot)?;
        writeln!(s, "{pad}{dst} = {};", val(block.yields[i])).unwrap();
    }
    Ok(())
}

fn gen_ops(s: &mut String, k: &Kernel, body: &[SSANode], depth: usize) -> Result<(), CompileError> {
    let pad = "    ".repeat(depth);
    for &nid in body {
        let op = k.op(nid);
        match &op.opcode {
            SSAOpCode::ConstU32(c) | SSAOpCode::ConstField(c) => {
                writeln!(s, "{pad}const uint32_t {} = {c}u;", val(op.results[0])).unwrap();
            }
            SSAOpCode::Bin(bop, ty) => {
                let a = val(op.operands[0]);
                let b = val(op.operands[1]);
                writeln!(
                    s,
                    "{pad}const uint32_t {} = {};",
                    val(op.results[0]),
                    bin_str(*bop, *ty, &a, &b)
                )
                .unwrap();
            }
            SSAOpCode::Select => {
                writeln!(
                    s,
                    "{pad}const uint32_t {} = {} ? {} : {};",
                    val(op.results[0]),
                    val(op.operands[0]),
                    val(op.operands[1]),
                    val(op.operands[2])
                )
                .unwrap();
            }
            SSAOpCode::Loop { bound } => {
                // The results double as the mutable loop-carried slots.
                for (i, res) in op.results.iter().enumerate() {
                    writeln!(s, "{pad}uint32_t {} = {};", val(*res), val(op.operands[i])).unwrap();
                }
                let iv = val(op.block.operands[0]);
                writeln!(
                    s,
                    "{pad}for (uint32_t {iv} = 0u; {iv} < {bound}u; ++{iv}) {{"
                )
                .unwrap();
                for (i, carried) in op.block.operands[1..].iter().enumerate() {
                    writeln!(
                        s,
                        "{pad}    const uint32_t {} = {};",
                        val(*carried),
                        val(op.results[i])
                    )
                    .unwrap();
                }
                gen_ops(s, k, &op.block.body, depth + 1)?;
                for (i, y) in op.block.yields.iter().enumerate() {
                    writeln!(s, "{pad}    {} = {};", val(op.results[i]), val(*y)).unwrap();
                }
                writeln!(s, "{pad}}}").unwrap();
            }
            other @ (SSAOpCode::Par { .. } | SSAOpCode::Alloc { .. } | SSAOpCode::Sync) => {
                unreachable!("statement-level op {other:?} inside a par block")
            }
        }
    }
    Ok(())
}

fn bin_str(op: BinOp, ty: ScalarType, a: &str, b: &str) -> String {
    if ty == ScalarType::BabyBear {
        match op {
            BinOp::Add => format!("bb_add({a}, {b})"),
            BinOp::Sub => format!("bb_sub({a}, {b})"),
            BinOp::Mul => format!("bb_mul({a}, {b})"),
            _ => unreachable!("op {op:?} is not defined on BabyBear"),
        }
    } else {
        let c_op = match op {
            BinOp::Add => "+",
            BinOp::Sub => "-",
            BinOp::Mul => "*",
            BinOp::Div => "/",
            BinOp::Rem => "%",
            BinOp::Lt => "<",
            BinOp::Le => "<=",
            BinOp::Eq => "==",
        };
        match op {
            BinOp::Lt | BinOp::Le | BinOp::Eq => format!("(uint32_t)({a} {c_op} {b})"),
            _ => format!("{a} {c_op} {b}"),
        }
    }
}

/// C lvalue for one access: the buffer element at the access's index. The
/// buffer's linear layout (logical -> physical) is applied when non-trivial.
fn access_str(
    p: &KernelProgram,
    access: &Access,
    vid: SSARes,
    slot: &str,
) -> Result<String, CompileError> {
    let decl = p.buffer(access.buf);
    if decl.kind == BufferKind::Register {
        // Each par point owns one element, held in the thread's slot for the
        // point's sequential step.
        let identity = matches!(
            &access.index,
            IndexMap::Affine { expr, .. } if *expr == Quast::sym(VarId(vid.0))
        );
        if !identity {
            return Err(CompileError::Codegen(format!(
                "register buffer {} accessed at an index other than the par's own",
                decl.name
            )));
        }
        return Ok(format!("r{}[{slot}]", access.buf.0));
    }
    let logical = match &access.index {
        IndexMap::Linear(ll) => ll_apply_str(ll, &val(vid)),
        IndexMap::Affine { expr, bounds } => expr.emit(bounds, &mut CStrEmitter)?,
    };
    Ok(match &decl.layout {
        Some(l) if !l.is_identity() => {
            format!(
                "b{}[{}]",
                access.buf.0,
                ll_apply_str(l, &format!("({logical})"))
            )
        }
        _ => format!("b{}[{logical}]", access.buf.0),
    })
}

/// C expression applying a [`LinearLayout`] to `x`: the XOR of the bases
/// selected by the bits of `x`.
fn ll_apply_str(layout: &LinearLayout, x: &str) -> String {
    layout
        .bases
        .iter()
        .enumerate()
        .map(|(i, &b)| format!("((({x} >> {i}) & 1u) * {b}u)"))
        .collect::<Vec<_>>()
        .join(" ^ ")
}

/// C expression for a buffer pointer inside `run`, respecting constness.
fn buf_arg(p: &KernelProgram, buf: BufId, writable: bool) -> String {
    let cq = if writable { "" } else { "const " };
    match p.buffer(buf).kind {
        BufferKind::Input(k) => format!("({cq}uint32_t*)p->inputs[{k}]"),
        BufferKind::Output(k) => format!("({cq}uint32_t*)p->outputs[{k}]"),
        BufferKind::Scratch { offset } => {
            format!("({cq}uint32_t*)((char*)p->scratch + {offset})")
        }
        BufferKind::Shared | BufferKind::Register => {
            unreachable!("kernel-local buffers are never kernel parameters")
        }
    }
}

fn gen_host(s: &mut String, p: &KernelProgram) {
    let n_in = p.input_bufs.len();
    let n_out = p.output_bufs.len();
    let in_sizes = p
        .input_bufs
        .iter()
        .map(|&b| format!("{}ull", p.buffer(b).size_bytes()))
        .collect::<Vec<_>>()
        .join(", ");
    let out_sizes = p
        .output_bufs
        .iter()
        .map(|&b| format!("{}ull", p.buffer(b).size_bytes()))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(
        s,
        r#"struct Prog {{
    void* inputs[{in_cap}];
    void* outputs[{out_cap}];
    void* scratch;
}};

static const uint64_t kInputSizes[{in_cap}] = {{{in_sizes}}};
static const uint64_t kOutputSizes[{out_cap}] = {{{out_sizes}}};

extern "C" Prog* make_module() {{
    Prog* p = new Prog;
    std::memset(p, 0, sizeof(Prog));
    return p;
}}
extern "C" void destroy_module(Prog* p) {{ delete p; }}
extern "C" uint64_t scratch_size(Prog*) {{ return {scratch}ull; }}
extern "C" uint64_t num_outputs(Prog*) {{ return {n_out}ull; }}
extern "C" uint64_t output_size(Prog*, uint64_t i) {{ return kOutputSizes[i]; }}
extern "C" uint64_t num_inputs(Prog*) {{ return {n_in}ull; }}
extern "C" uint64_t input_size(Prog*, uint64_t i) {{ return kInputSizes[i]; }}
extern "C" void set_input(Prog* p, uint64_t i, void* ptr) {{ p->inputs[i] = ptr; }}
extern "C" void set_output(Prog* p, uint64_t i, void* ptr) {{ p->outputs[i] = ptr; }}
extern "C" void set_scratch_buf(Prog* p, void* ptr) {{ p->scratch = ptr; }}
"#,
        in_cap = n_in.max(1),
        out_cap = n_out.max(1),
        in_sizes = if n_in == 0 { "0ull".into() } else { in_sizes },
        out_sizes = if n_out == 0 { "0ull".into() } else { out_sizes },
        scratch = p.scratch_bytes,
        n_out = n_out,
        n_in = n_in,
    )
    .unwrap();

    writeln!(
        s,
        "extern \"C\" cudaError_t run(Prog* p, cudaStream_t stream) {{"
    )
    .unwrap();
    for k in &p.kernels {
        let args = k
            .params
            .iter()
            .map(|&(buf, writable)| buf_arg(p, buf, writable))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            s,
            "    {}<<<dim3({}u), dim3({}u), 0, stream>>>({args});",
            k.name, k.grid.bound, k.block
        )
        .unwrap();
        writeln!(
            s,
            "    {{ cudaError_t err = cudaGetLastError(); if (err != cudaSuccess) return err; }}"
        )
        .unwrap();
    }
    writeln!(s, "    return cudaSuccess;\n}}").unwrap();
}
