name: Build and Serve Crate Docs

on:
  push:
    branches: [main]
    tags:
      - v*.*.*
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/docs.yml"

jobs:
  docs:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=8cpu-linux-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build documentation
        run: cargo +nightly doc --workspace --no-deps
        env:
          # taken from https://github.com/paradigmxyz/reth/blob/main/.github/workflows/book.yml
          RUSTDOCFLAGS: --enable-index-page -Zunstable-options

      - name: Install s5cmd
        run: |
          source ci/scripts/utils.sh
          install_s5cmd

      - name: Sync static S3 bucket
        env:
          S3_BUCKET: ${{ vars.CRATE_DOCS_S3_BUCKET }}
        run: |
          cd target/doc
          s5cmd sync . s3://${S3_BUCKET%/}/static/
